language: python

python:
  - '3.6'

install:
  - pip install -U tox-travis
  - pip install -e .[dev]

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: n4RqLWPdxInJowE3hFLQkWs+OT5Jjxy9YhWuDdKu8Fme36FSPUyb/kFtHOzxeUDDw3LfXlBQicTR+wMygwh9P+vOwgpGke76J6QML3UCa1oyx5O6lHjY12ebgDFLZssaA/ZJPp6smLHmVWI8BO3gK8HP3rLARAEHis21Otztoe37qjZigt2xJyLzbd61iWTTXGvn2FWK12e/Sw/PIMk9PJ6+OpeE0IEnXDu2z91wFiZH917hI2WzEweHDoDCl1sHLjkfOAkHtMZegd9eWDeIj4/GeXFgd68o7Q15vNgUBKWNXOgyabZrcV545aw1f9jKPuwvd9Gj0gO4x58AmIEilPf49REsGt8/I56CE6EoWW7f1kCZr5SKfGhkCHRmWqzkC3yV01afkLaxQsqYmUalMrHOrnBHDp/ieeS6/Kg8kHJp43MdYcBbjo9P+vd1cW10gA2F5QOE+aCeuiJvFHTsBYqQrQl4ractYAKfWJsVCQVG1RR0B/dUc5qFCr535m3Hy7dr+dCdEzsLc3AFYB5cMnDolmOMH+DpPrd7DN/ecN6FbrqKydaOQmuTnTnI/Il1KwoMyav15bkAt1Igo6zxcpTh8uuiMZNXOSX+fMeRTB7kJpyLlY4PVj8rwS411y/tB0IB4nmrq7YdXmsG/qUSWJ1yu5lydCrKDuXv5repVjU=
  on:
    tags: true
    branch: master
    python: 3.6
