language: python

python:
  - '3.6'
install:
  - pip install -U tox-travis
  - pip install -e .[dev]

script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: COKq2/loJuJP1Wiyvsr10WEvixGuitANZB1vyh6vfhZ7UTNSundgjW04TfcoSobme1PhjPSEOqg6HK+ZloH3g8QHohmV5PSb3LWD/+kFE5F+dNFp9wRjjx1hdN8YFRDLgKKUDQlHroydWPdq4Mz0L1yLWpqC7wtAy/ggBiAya8kAxNQ1gXL6PCl4vAQjPD0ab5ry8cMlaRiNGCWivu68IAQ5ZdU7hrqFpz+xD/H8aLO9/YrNST3vHCAYEZRh57B61wFPfCoPRQJITrLrnXGZqqtSyzlgKbm1WLk//OjBdR0wltel74QuV1KNzvZOoV6jYxl23GXArO0FY+et8O1T2EVRRTd43C3PHsswlsjE6270v4TLEv3nuIPexQrlbL+s21BSOChrz1wkorArv1ziaS6kJnf6Gl4IGO4Lm3T8TjqMoOKubs9+j7f8JQXgASAYVmvwbAR+BZ4zmAf0KJlzvpKFmrUXp2w6RYcKlC9yQVVBS1/g3N731i10yrWM8NwJHTrC3FbA5+/DYRasnu2chKpGsn8ZYYCW/QFizC2Wn6TUL1RcoW+/2YcBrJEXSVDo3QZanxvBOu7b1fU6WuOqIp3gVl8G+RLffMIFvBC3L0iV8M2lDqayDKWA96Oq4j3DeccOdN+pDOSaVx6wOZkF0rmvX1VOVXBXlz2sciepxOo=
  on:
    tags: true
    branch: master
    python: 3.6
