language: python

python:
  - '3.6'
install:
  - pip install -U tox-travis
  - pip install -e .[dev]

script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: OpenXbox
  password:
    secure: Hp3sIBJ9vTLd0DHRnL3L7yhSi24fJpFkfONbHh/HhlNxNUNtVwGR2PqJ+VIHsVaz+Y8RNtyHW7Y9Veoo3slRyqGueozrzPia0wl+LBnVGEB2ukwxe/p+RFogksJrnh+hA175lwwGkXJPfSWvv2UfP+5tOwImvDR7bmqki8G9lN51U0Ve+X5v2vA5unZVC9xhkToZCO7tB8n4+B2IxHig+VxnHTv7DKNSHgm5y1VgNbfD1ueG7bqQ4sQY3pi6nHLvJxWr7OkohyZOIoeDOGDqthirE/gGmCRm+5R5R6VwNHGxpfy5sGvJtT2e9JAfesQVO88jpdtVGqUbaXUW0VIsfhx06tFP1ti5aAvIByIdbIUNteUHse+o7myhtWx1BB0cJW7O7Tcdg7clcZJHEAsTq2mn16U5HjDFeKf0QGR91E4K+u7JI2VM91s+EGDFho1Z1yQ1oUeQdV72EC8GTBn/iW6SRcRLbh2LLemT4SZktwT9EbxUsaawoFfh+8TQ/R2/tyIS2LVP2BNs/sd3XSRo/D3xk/prUMaGgJNYD95godXUmAzLVDghFCqdsLk3qKY5Im6TMTer/su8ShnqB1K6r4t5XKCVH/iMGpTJA2TvJxzCv4CmOGgEBLelD9odmtG7UabJrKvKgi63rS18tw/i6j1zo3XiPxHVguHZVrj+CfU=
  on:
    tags: true
    branch: master
    python: 3.6
